# Site settings
title: Italien
client:
  name: Unentdeckte Schätze
  link: "http://www.italia.it"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Begeben Sie sich auf die Spuren der Etrusker, finden Sie einzigartige Relikte vergangener Zeiten wie die apulischen Trulli, erleben Sie das authentische Flair italienischer Dörfer in kleinen Borghi oder spüren Sie beim Genuss der Cucina italiana das mediterrane Lebensgefühl

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/italien" # the subpath of your site, e.g. /blog/
img:     "/de/italien/_assets/img"
css:     "/de/italien/_assets/css"
js:      "/de/italien/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
